services:
  dysfunctional-staging:
    build:
      target: development
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    environment:
      - HOST_UID=${HOST_UID:-1000}
      - HOST_GID=${HOST_GID:-1000}
      - APP_ENV=${APP_ENV:-local}
      - HOST_PATH=${PWD}
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    tty: true
    labels:
      - 'tsbridge.enabled=true'
      - 'tsbridge.service.name=dysfunctional-staging'
      - 'tsbridge.service.port=80'
    networks:
      - tsbridge

networks:
  tsbridge:
    external: true
