services:
    dysfunctional:
        build:
            target: development
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env.docker
        environment:
            # Pass host user/group IDs for volume permissions
            - HOST_UID=${HOST_UID:-1000}
            - HOST_GID=${HOST_GID:-1000}
            - APP_ENV=${APP_ENV:-local}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - .:/app
            - ../functions:/functions
        restart: unless-stopped
        labels:
            - "tsbridge.enabled=true"
            - "tsbridge.service.name=dysfunctional"
            - "tsbridge.service.port=80"
        networks:
            - tsbridge

networks:
    tsbridge:
        external: true
