# yaml-language-server: $schema=../../../schemas/function.schema.json

function:
  name: Handle a POST request
  description: This is a sample function
  route: /test
  method: POST
  runtime: language/php/serversideup/8.4/cli
  entrypoint: entrypoint.php
